# 基础配置
server:
  port: 9090

# mysql，redis，mail配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddedss?useUnicode=true&characterEncoding=utf8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.qq.com


# mybatis plus 配置
mybatis-plus:
#  configuration:
#     输出日志到控制台
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1

