# 基础配置
server:
  port: 9090

# mysql，redis，mail配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddedss?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.qq.com
    username: 1732781024@qq.com
    password: ewbsjajcxptvcaca


# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: 1
      logic-not-delete-value: 0

