server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddedss?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: 1
      logic-not-delete-value: 0

